#pragma once

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 200

#define ADAPTIVE_TERM 300
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 100
#define QUICK_TAP_TERM_PER_KEY

#define COMBO_TERM 30
#define COMBO_HOLD_TERM 200
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 0

#define PERMISSIVE_HOLD
