#pragma once

#define ADAPTIVE_TERM 300
#define TAPPING_TERM 300
#define TAPPING_TOGGLE 2
#define QUICK_TAP_TERM 150
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define COMBO_TERM 26
#define COMBO_TERM_PER_COMBO
#define COMBO_HOLD_TERM 300
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 0

#define PERMISSIVE_HOLD
