#pragma once

#define QUICK_TAP_TERM 150
#define TAPPING_TERM 150
#define TAPPING_TOGGLE 2

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define COMBO_TERM 26
#define COMBO_TERM_PER_COMBO
#define COMBO_HOLD_TERM TAPPING_TERM
#define COMBO_MUST_TAP_PER_COMBO

#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define FLOW_TAP_TERM 50
